### ISSUE TITLE
编译报错了

### ISSUE THREAD

**Issue by Xiaobaishushu25** [heng30/slint-template#1]
error: Change callbacks are experimental and not yet implemented in this version of Slint
   --> E:\WorkSpace\Rust\RR\slint-template\ui\base\icon-btn.slint:115:9
    |
115 |         changed has-hover => {
    |         ^
这个如何解决呢。

**Comment by heng30** [comment]
看Makefile里，有一个环境变量SLINT_ENABLE_EXPERIMENTAL_FEATURES=1。建议用make进行编译。slint也要用最新的版本。

**Comment by han1548772930** [comment]
```
SLINT_STYLE=fluent SLINT_ENABLE_EXPERIMENTAL_FEATURES=1 cargo build --release --features=desktop
'SLINT_STYLE' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
make: *** [Makefile:30: desktop-build-release] Error 1
```

**Comment by han1548772930** [comment]
web里面是100vh不是100wh

**Comment by heng30** [comment]
> ```
> SLINT_STYLE=fluent SLINT_ENABLE_EXPERIMENTAL_FEATURES=1 cargo build --release --features=desktop
> 'SLINT_STYLE' 不是内部或外部命令，也不是可运行的程序
> 或批处理文件。
> make: *** [Makefile:30: desktop-build-release] Error 1
> ```
在windows可以使用git bash终端调用make命令。 或者自己设置`SLINT_STYLE=fluent SLINT_ENABLE_EXPERIMENTAL_FEATURES=1` 这两个环境变量。例如：`setx [variable_name] "[variable_value]"`
